services:
  # Web Service - لوحة التحكم Dashboard
  - type: web
    name: egyptian-voter-inquiry-bot
    env: docker
    plan: free
    region: frankfurt
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PORT
        value: "10000"
      - key: SPREADSHEET_ID
        sync: false
        # قم بتعيين هذا في لوحة تحكم Render
